# Generated by Django 5.1.5 on 2025-09-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
    ]
